"""
    Basic analysis of the data generated by playlist_download.py
"""

import pandas as pd
import numpy as np
import playlist_download
import matplotlib.pyplot as plt

from playlist_download import download_metadata

def trendline(x, y, x_label, y_label, title):

    trend = np.polyfit(x, y, 1)
    trend_fn = np.poly1d(trend)

    plt.scatter(x, y)
    plt.plot(x, trend_fn(x), 'r')
    plt.xlabel(x_label)
    plt.ylabel(y_label)
    plt.title(title)
    plt.grid(alpha=0.4)
    plt.show()

df = download_metadata('Douwe Prog')

time_diff = (df['add_date'] - df['add_date'][0]).astype('timedelta64[D]')

position = (df['duration'] / 15000).round()

plt.scatter(position, df['duration']/1000)
plt.plot(np.linspace(0, 102, 102), np.linspace(0, 102, 102) * 15, 'r')
plt.xlabel('Track position')
plt.ylabel('Track duration (s)')
plt.grid(alpha=0.4)
plt.show()

